version: '3'
services:
  feedback-service:
    image: ed-application/feedback-service:1.0
    build: ./feedbacks/
    container_name: feedback-service
    ports:
      - "8084:8084"
    networks:
      - application-backend-network
    depends_on:
      - postgres-feedback-db

  postgres-feedback-db:
    image: postgres:12.3-alpine
    container_name: feedback-db
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=feedback_db
    ports:
      # don't expose ports in production
      - "8053:5432"
    networks:
      - application-backend-network
    volumes:
      - ./database/Feedback.sql:/docker-entrypoint-initdb.d/feedback.sql  # file name in docker container should also be changed right?

networks:
  application-backend-network:
    driver: bridge
    name: application-backend-network