version: '3'
services:
  patient-service:
    image: ed-application/patient-service:1.0
    build: ./patient-management/
    container_name: patient-service
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - postgres-patient-db

  postgres-patient-db:
    image: postgres:12.3-alpine
    container_name: patient-db
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=patient_db
    ports:
      # don't expose ports in production
      - "8050:5432"
    networks:
      - app-network
    volumes:
      - ./database/Patient.sql:/docker-entrypoint-initdb.d/patient.sql  # file name in docker container should also be changed right?

networks:
  app-network:
    driver: bridge
    name: app-network